pipeline:
  identifier: Build_Harness_React_1699349821380
  name: Build Harness_React
  orgIdentifier: default
  projectIdentifier: Harness_React
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1699349733030
        repoName: Harness_React
        build: <+input>
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_build
                  spec:
                    shell: Sh
                    command: npm run build
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: <+input>
                    repo: <+input>
                    tags:
                      - "0.1"
                    dockerfile: Dockerfile
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
